### ISSUE TITLE
ENOSPC: no space left on device

### ISSUE THREAD

**Issue by abitrolly** [Rich-Harris/packd#150]
https://bundle.run/nearley@2.20.1/lib/compile.js
```
ENOSPC: no space left on device, mkdir '/tmp/2210d0e2b98537a4a2857bb8f534a1d96b1eea1d'
```

**Comment by abitrolly** [comment]
What is the size of all files hosted by `bundle.run` currently? Are there any historical metrics? What is the CDN being used? Is it expensive? Many questions while waiting for it..

**Comment by xtuc** [comment]
I fixed the issue, https://bundle.run/nearley@2.20.1/lib/compile.js is working now.

**Comment by abitrolly** [comment]
@xtuc still getting the same error for other files in the package.

https://bundle.run/nearley@2.20.1/lib/generate.js
https://bundle.run/nearley@2.20.1/lib/nearley-language-bootstrapped.js

**Comment by xtuc** [comment]
I invalidated the cache for both files and it's working now.

**Comment by abitrolly** [comment]
Now I can finally use it here - https://observablehq.com/@abitrolly/moo-and-nearley )

@xtuc thanks!
