### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by PaulMaly** [Rich-Harris/packd#63]
```
Cannot find module 'svelte' from '/var/app/current/.tmp/f3329e1c32fd9bfba58cd0a0b059dac7604002c5/package'
```

**Comment by xtuc** [comment]
It's working on my side, it's likely a cached error. I'll invalid the cache.

**Comment by xtuc** [comment]
Caches were invalidated; https://bundle.run/svelte or https://bundle.run/svelte@2.16.0 should work now.

**Comment by PaulMaly** [comment]
@xtuc Seems still not working. Maybe because my package uses Svelte 3 alpha version?

**Comment by xtuc** [comment]
Could you please give me the exact URL you are using?

**Comment by PaulMaly** [comment]
https://bundle.run/svelte-morphing-modal@1.0.0
https://www.npmjs.com/package/svelte-morphing-modal

New experimental package from Svelte 3.

**Comment by xtuc** [comment]
I see the following error:
```
ENOENT: no such file or directory, open '/var/app/current/.tmp/f3329e1c32fd9bfba58cd0a0b059dac7604002c5/package/index.mjs.js'
```

Rollup (which bundle.run uses) will pick up the module entry `index.mjs` and search for it on the disk, but it seems that it's adding a `.js`. That's a bug, would you mind sending a PR to fix it?

**Comment by PaulMaly** [comment]
Which version of Rollup bundle.run uses? Seems,`.mjs` files now supported by Rollup: https://github.com/rollup/rollup/issues/1894

**Comment by PaulMaly** [comment]
Hm, btw, are you sure that problem in `.mjs` support? Because [@sveltejs/svelte-virtual-list](https://github.com/sveltejs/svelte-virtual-list) works (https://bundle.run/@sveltejs/svelte-virtual-list@2.2.1). This package also uses `index.mjs` as a module.

**Comment by xtuc** [comment]
i'm still having
```
Cannot find module 'svelte' from '/var/app/current/.tmp/f3329e1c32fd9bfba58cd0a0b059dac7604002c5/package'
```

but `svelte` is not listed as a prod dependecy https://github.com/PaulMaly/svelte-morphing-modal/blob/f7fa4af3be41616edecb3bcea63385e7670c76ea/package.json#L34. Could you please move it and try again?
